name: With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Linux and MacOS
          start: npm start
      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
