name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  Simple-deployment-pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm first
        run: npm install -g pnpm@9
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Check style
        run: pnpm run eslint
      - name: Build
        run: pnpm run build
      - name: Install cypress
        uses: CYPRESS_CACHE_FOLDER=~/cypress_cache cypress install
      - name: E2E Test
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/poke.spec.cy.js
          start: pnpm run start-prod
          command: pnpm run test:e2e
          wait-on: http://localhost:5000
